language: node_js

cache:
  directories:
    - ~/.npm
    - node_modules

notifications:
  email: false

node_js:
  - '11'
  - '10'
  - '8'

install:
  - yarn install

after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
